### ISSUE TITLE
Unable to download intropolis.v1.hg19.tsv.gz

### ISSUE THREAD

**Issue by DavidsonLabCHOP** [nellore/intropolis#5]
Hi, thanks for releasing and maintaining this great resource.  In the past i have downloaded your "intropolis.v1.hg19.tsv.gz" using the provided bit.ly link "**http://bit.ly/1SfBRTi**".  However today when i attempted this again the download repeatedly failed with the following message.  

```
--2021-07-27 12:28:41--  (try:20)  http://bit.ly/1SfBRTi
Connecting to bit.ly (bit.ly)|67.199.248.11|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Giving up.
```

Is there another place that I can access this file?  

Thanks again for making this great resource available to the scientific community!

**Comment by BenLangmead** [comment]
This worked for me just now.  It may simply be an intermittent issue.  Could you try again?  And if it doesn't work with the bit.ly URL, try the ultimate URL ftp://ftp.ccb.jhu.edu/pub/langmead/sra_junctions/intropolis.v1.hg19.tsv.gz.

Best,
Ben

**Comment by DavidsonLabCHOP** [comment]
Thanks for your quick reply and for providing an alternate URL.  I tried this but it also doesn't work. In addition to trying to directly download the file with wget and from a browser i tried an FTP client (fetch).  Fetch prompted me to input a username and password to access the ftp://ftp.ccb.jhu.edu domain. It seems like maybe I need to have credentials for ftp://ftp.ccb.jhu.edu in order to login to access this?  Is it available from a publicly accessible link?

**Comment by nellore** [comment]
Hi there! If you need that version of intropolis, you can also access it from figshare: https://figshare.com/articles/dataset/intropolis_exon-exon_junctions_across_publicly_available_RNA-seq_samples_on_the_Sequence_Read_Archive/3811680/1 . Otherwise, if you simply want junctions across tons of samples on SRA--more than in that compilation--it's highly recommended you check out Snaptron: http://snaptron.cs.jhu.edu/. The data sourcing that webservice is available at http://snaptron.cs.jhu.edu/data/.
